webERP-team/webERP

- PcAssignCashTabToTab.php
- PcAssignCashToTab.php
- PcAuthorizeExpenses.php
- PcClaimExpensesFromTab.php
- PcReportExpense.php
- PcReportTab.php
- PcTabExpensesList.php
- doc/Manual/ManualPettyCash.html
- sql/mysql/upgrade4.14.1-4.14.2.sql
Receipt upload filenames now hashed for improved security & new expenses claim field 'Business Purpose'
Includes new database table 'pcreceipts', and new database column 'pcashdetails.purpose'.
Inspired by code by @timschofield.
> Petty Cash - Receipt upload filenames now hashed 

- includes/InputSerialItemsFile.php
Forum reference: http://www.weberp.org/forum/showthread.php?tid=8113
> Fix issue reported by Jeff Harr in the forums.

- includes/header.php
Move the dashboard link from the AppInfoDiv into the QuickMenuDiv. This option will now appear between the Main Menu and Customers options.
This change also removes an old comment block and the SVN $Id line reference.
> Move dashboard link.

- reportwriter/WriteReport.inc
- reportwriter/admin/defaults.php
- reportwriter/admin/forms/ReportsCritSetup.html
- reportwriter/languages/en_US/reports.php
Additional tweaks to the previous reportwriter changes.
> PaulB reportwrite mods, part 2

- reportwriter/WriteReport.inc
- reportwriter/admin/forms/ReportsCritSetup.html
- reportwriter/languages/en_US/reports.php
Third round of "Prior Period" changes.
> PaulB reportwriter mods part3

- AnalysisHorizontalIncome.php
- GLProfit_Loss.php
- GLTagProfit_Loss.php
Update links to include FromPeriod and ToPeriod need by GLAccountInquiry.
Pault: along with this change removes unused $j variable from two files.
> PaulB: link updates to GLAccountInquiry, Pault: remove unused variable along with this change

- GLAccountInquiry.php
Reported in forums: http://www.weberp.org/forum/showthread.php?tid=8138
> PaulB: GLAccountInquiry: Fix that the script does not automatically show data

- DeliveryDetails.php
Reported in the forums: http://www.weberp.org/forum/newreply.php?tid=8134
> Jeff Harr: Sales Order required date not reflected in Work Order.

- AgedSuppliers.php
Reported in forums: http://www.weberp.org/forum/showthread.php?tid=8136
> PaulB: Misspelling of Aged Suppliers Report

- Logout.php
Change:
$name => $Name
$cookie_info => $CookieInfo
... to meet coding standards.
Also, add more commentary/information details.
> Meet coding standards and more commentary. 

- AgedSuppliers.php
- DeliveryDetails.php
- GLAccountInquiry.php
- Logout.php
Files Changed:
api/api_debtortransactions.ph
api/api_stock.php
api/api_workorders.php
Correct function call from GetNextTransactionNo() to GetNextTransNo()
Change variable names to conform to coding standards
Change code layout to conform to coding standards
Fixes issue no #24 see - #24
> Tim's fixes to issue #24 https://github.com/timschofield/webERP-svn/issues/24 

- BOMs_SingleLevel.php
- ConfirmDispatch_Invoice.php
- CounterReturns.php
- CounterSales.php
- Credit_Invoice.php
- Prices.php
- RecurringSalesOrdersProcess.php
- SelectCreditItems.php
- Shipments.php
- SupplierTenderCreate.php
- SupplierTenders.php
- api/api_debtortransactions.php
- api/api_salesorders.php
- api/api_salestypes.php
- api/api_webERPsettings.php
- includes/DefineOfferClass.php
- includes/DefineShiptClass.php
- includes/DefineTenderClass.php
- includes/GetSalesTransGLCodes.inc
- includes/Z_POSDataCreation.php
Another round of removing unused $db parameters.
> Remove more unused $db parameters

- Z_MakeNewCompany.php
1. Adds Journal.xml and ShippingLabel.xml to copy
2. Organizes copied XML files alphabetically (to ease referencing)
3. Organizes new directory creation alphabetically (to ease referencing)
4. echo keyword reduction
...and other minor formatting.
>  Add XML files to new company copy 

- SelectOrderItems.php
Includes Jeff Harr's tabindex attribute removal.
Plus other merges.
> Updates from head fork.

- Z_MakeNewCompany.php
- includes/session.php
Changes from Paul Becker and @timschofield:
**StockQuantityByDate.php**
1. Show only items where the stock balance at location is greater than zero.
2. Show whether the item is controlled or not.
3. Add in a checkbox to restrict the report to only items with stock balances greater than zero.
4. Re-format the code per guidelines
**SelectOrderItems.php**
1. The form item for the stockid and the quantity were out of sync especially if there were frequently ordered items shown on the selection screen.
2. This fix ensures all stock items on the search screen, FOI and searched for have unique numbers and the numbers are kept in sync.
3. Reported, and testing of the fix done by Jeff Harr
References : http://www.weberp.org/forum/showthread.php?tid=8144
> Merges from head fork. (see comment for details)

- Z_Fix1cAllocations.php
- xmlrpc/src/Autoloader.php
- xmlrpc/src/Client.php
- xmlrpc/src/Encoder.php
- xmlrpc/src/Helper/Charset.php
- xmlrpc/src/Helper/Date.php
- xmlrpc/src/Helper/Http.php
- xmlrpc/src/Helper/Logger.php
- xmlrpc/src/Helper/XMLParser.php
- xmlrpc/src/PhpXmlRpc.php
- xmlrpc/src/Request.php
- xmlrpc/src/Response.php
- xmlrpc/src/Server.php
- xmlrpc/src/Value.php
- xmlrpc/src/Wrapper.php
XMLRPC library updated - just the necessary files
> updated https://github.com/gggeek/phpxmlrpc

- Dashboard.php
- doc/CHANGELOG.md
Plus missing entries added to CHANGELOG.md.
Reported and fixed by Paul Becker.
http://www.weberp.org/forum/showthread.php?tid=8161
> Fixed bank account and related data visible to an unauthorised user in Dashboard.php

- SelectPickingLists.php
Add script description, ViewTopic and BookMark.
> Add script description, ViewTopic and BookMark

- doc/Manual/ManualGeneralLedger.html
Add section for the "Graph of Account Transactions" script in the manual.
> Add info to the manual.

- BankAccountBalances.php
- doc/Manual/ManualGeneralLedger.html
Add info to script and to manual.
> Add info to script and to manual

- SelectContract.php
- doc/Manual/ManualContracts.html
Add "id" for $BookMark = 'SelectContract'.
> Add id for bookmark

- doc/Manual/ManualGeneralLedger.html
Add info to General Ledger manual.
> Add info to GL manual

- DailyBankTransactions.php
@PaulBecker's calculation fix.
> DailyBankTransactions.php calculation fix

- doc/CHANGELOG.md
Forgot to add reference to Paul Becker DailyBankTranactions calculation fix.
> Changelog update

- MRP.php
- doc/CHANGELOG.md
> BrianTMG calculation fix in MRP reorder inserts.

- DailyBankTransactions.php
- doc/CHANGELOG.md
Updated script by @timschofield has layout and other handling improvements.
> Apply Tim's updated DailyBankTransactions.php script

- PO_Header.php
- Suppliers.php
- sql/mysql/upgrade4.15-4.15.1.sql
Create the new field defaultshipper in the suppliers table
Amend Suppliers.php to update the new field
When entering a purchase order default to the shipper defined
in this new field.
> Tim's default shipper addition

- PDFQALabel.php
- PrintCustOrder_generic.php
- Z_CheckDebtorsControl.php
- doc/CHANGELOG.md
- includes/footer.php
Updates from the latest bug fixes.
> Add bug fixes only updates.

- doc/Manual/ManualEDI.html
Re-upload the missing ManualEDI.html file.
> Re-upload ManualEDI.html

- ConfirmDispatch_Invoice.php
Remove unneeded tabindexes and duplicate attribute "required" in tag Date On Invoice.
>  Remove tabindexes and duplicate html attribute

- ConfirmDispatch_Invoice.php
- css/professional-rtl/default.css
> Add currency name

- FormDesigner.php
- doc/Manual/ManualSetup.html
> Fix table overflow

- FormDesigner.php
Adds the <label> tag to provide a usability improvement (if the user clicks on the text within the <label> element, it toggles to the input element).
> Adds the <label> tag

- css/WEBootstrap/default.css
- css/aguapop/default.css
- css/default/default.css
- css/fluid/default.css
- css/fresh/default.css
- css/gel/default.css
- css/professional-rtl/default.css
- css/professional/default.css
- css/silverwolf/default.css
- css/wood/default.css
- css/xenos/default.css
For some class selectors: group them, fix class selector reference, replaces the HTML colour names with their HEX value, and sort attributes.
>  Clean up some class selectors in default.css

- includes/footer.php
Simplify the switch statement code. Group, simplify and clean up the echo statements.
> Simplify and clean up code

- PDFPriceList.php
- doc/Manual/ManualSalesTypes.html
Add option to show/hide obsolete items.
> Add option to show/hide obsolete items

- GoodsReceived.php
> Fix typing error

- PrintCustTransPortrait.php
- css/WEBootstrap/default.css
- css/aguapop/default.css
- css/default/default.css
- css/fluid/default.css
- css/fresh/default.css
- css/gel/default.css
- css/print.css
- css/professional-rtl/default.css
- css/professional/default.css
- css/silverwolf/default.css
- css/wood/default.css
- css/xenos/default.css
Add cascading style sheet class selector for sheet preview.
> Add class selector for sheet preview.

- PurchasesReport.php
Standardise PurchasesReport.php to SalesReport.php (part 2).
> Standardise PurchasesReport.php

- GLCashFlowsIndirect.php
- PDFPriceList.php
- PurchasesReport.php
- SalesReport.php
- WWW_Users.php
- doc/CHANGELOG.md
Simplify the field_help_text code, using in header.php: if(isset($_SESSION['ShowFieldHelp']) AND !$_SESSION['ShowFieldHelp']) { echo '.field_help_text {display:none;}'; }
> Change field_help_text code (part 1)

- doc/CHANGELOG.md
>  Update CHANGELOG.md

- GLBalanceSheet.php
- includes/MiscFunctions.php
Show correct periods in link to account inquiry
> Show correct periods in link to account inquiry

- DailyBankTransactions.php
- doc/CHANGELOG.md
In DailyBankTransactions.php, in input form, sorts bank accounts by name in bank account selection.
> Order by bankaccountname

- doc/CHANGELOG.md
> Updates CHANGELOG.md

- BankAccountBalances.php
- BankAccountUsers.php
- BankAccounts.php
- BankMatching.php
- BankReconciliation.php
- CounterReturns.php
- CounterSales.php
- DailyBankTransactions.php
- ImportBankTrans.php
- UserBankAccounts.php
- doc/CHANGELOG.md
Sort the bank accounts that are going to be shown.
> Sort the bank accounts

- GLBalanceSheet.php
- doc/CHANGELOG.md
Improve the readability of the script.
> Improve the readability of the script

- GLBalanceSheet.php
- GLCashFlowsIndirect.php
- GLProfit_Loss.php
- GLStatements.php
- sql/mysql/upgrade4.15-4.15.1.sql
Add a script to show a set of financial statements.
>  Show a set of financial statements

- GLBalanceSheet.php
- GLCashFlowsIndirect.php
- GLProfit_Loss.php
- GLStatements.php
Clean up and standardise scripts.
> Clean up and standardise scripts

- css/WEBootstrap/default.css
- css/aguapop/default.css
- css/default/default.css
- css/fluid/default.css
- css/fresh/default.css
- css/gel/default.css
- css/professional-rtl/default.css
- css/professional/default.css
- css/silverwolf/default.css
- css/wood/default.css
- css/xenos/default.css
Hides field help text and page help text for devices with a rendering width less than 768px (xs - Extra small devices - Phones).
> Hides help texts for extra small devices

- css/WEBootstrap/default.css
- css/aguapop/default.css
- css/default/default.css
- css/fluid/default.css
- css/fresh/default.css
- css/gel/default.css
- css/professional-rtl/default.css
- css/professional/default.css
- css/silverwolf/default.css
- css/wood/default.css
- css/xenos/default.css
Clean up the cascading style sheets.
> Clean up the CSS

- GLBalanceSheet.php
- GLCashFlowsIndirect.php
- GLProfit_Loss.php
- GLStatements.php
- css/WEBootstrap/default.css
- css/aguapop/default.css
- css/default/default.css
- css/fluid/default.css
- css/fresh/default.css
- css/gel/default.css
- css/professional-rtl/default.css
- css/professional/default.css
- css/silverwolf/default.css
- css/wood/default.css
- css/xenos/default.css
Clean up and standardise the class selector for sheet style view. In order not to alter the current styles, only the CSS "Default" has this class working (uncommented).
> Clean up and standardise sheet style view

- AnalysisHorizontalIncome.php
- AnalysisHorizontalPosition.php
Standardise buttons in AnalysisHorizontalIncome.php and AnalysisHorizontalPosition.php.
> Standardise buttons

- GLStatements.php
Simplify code in GLStatements.php.
> Simplify code in GLStatements.php

- css/fluid/default.css
- css/fresh/default.css
- css/professional-rtl/default.css
- css/professional/default.css
- css/wood/default.css
Fix height in #QuickMenuDiv li. Useful in small devices.
> Fix height in #QuickMenuDiv li

- GLStatements.php
To fix not uploaded GLChangesInEquity.php and GLNotes.php.
> Fix unuploaded scripts

- AnalysisHorizontalIncome.php
- AnalysisHorizontalPosition.php
- GLAccountGraph.php
- GLBalanceSheet.php
- GLCashFlowsIndirect.php
- GLProfit_Loss.php
- GLStatements.php
- GLTagProfit_Loss.php
- GLTrialBalance.php
- SalesGraph.php
> Standardise code

- GLTransInquiry.php
fix where discount is entered at payment but not included in the report line item calculation
> fix where discount is entered at payment but not included

- CustomerAllocations.php
fix to display and allow user to perform allocation on receipts with amount zero but discount is non zero
> allow user to perform allocation on receipts with amount zero but discount is non zero

- CounterSales.php
1. improve counter sales quick entry flow by pre-fetching stockmaster list and auto fill to the quick entry table
2. user interface to show amount received and the change amount due
> improve counter sales quick entry flow

- SuppCreditGRNs.php
add missing parameter for Add_GRN_To_Trans()
> fix missing parameter for Add_GRN_To_Trans

- StockMovements.php
fix query for stock movement records not returned when there is no link to custbranch db table
P.S. setting this request to merge to master as I not sure if fix is to be merged to which branch
> fix stock movement records missing in report

- CounterSales.php
- javascripts/CounterSalesFunctions.js
refactor code counter sales javascript functions to CounterSalesFunctions.js
> counter sales javascript functions to CounterSalesFunctions.js

- SupplierInvoice.php
fix purchase order item to flag as completed when automatically receive purchase orders
> fix purcahse order item to flag as completed 

- Z_DeleteSalesTransActions.php
Z_DeleteSalesTransActions.php
Add new table to be emptied
Change truncates to deletes as some sql modes do not allow the truncation of tables when a foreign key is present
http://www.weberp.org/forum/showthread.php?tid=8360
> Fix utility script for new tables

- PageSecurity.php
PageSecurity.php
$AlloDemoMode changed to $AllowDemoMode
> Fix typo in variable name

- InternalStockRequest.php
InternalStockRequest.php
http://www.weberp.org/forum/showthread.php?tid=8366
> Fix inconsistent casing in variable names

- StockLocTransferReceive.php
- StockTransfers.php
Fix the insert of incoming and outgoing inventory GL transactions at StockTransfers.php
> GL Posting Fixes for Stock Transfers

- StockCounts.php
add alternative method for user to enter stock counts by importing csv file
> add alternative method for user to enter stock counts

- PDFStockCheckComparison.php
insert missing standard cost field when performing adjustment for stock check
> insert missing standard cost field

- api/api_locations.php
return api data format to include integer code as described in the [Manual](http://www.weberp.org/weberp/ManualContents.php?ViewTopic=APITutorial)
> return api data format to include integer code

- Dashboard.php
other sales people when a customer has more than one branch
with different sales people attached.
Dashboard.php
See:
http://www.weberp.org/forum/showthread.php?tid=8382
> Fix the bug whereby sales person invoices were divulged to

- UserSettings.php
- WWW_Users.php
- includes/LanguageSetup.php
- includes/MiscFunctions.php
- install/index.php
Improve language check to avoid potential LFI issue.
Reported by: https://lyhinslab.org
> Fix potential LFI issue

- includes/header.php
> Fix the link to the manual page

- Z_ImportDebtors.php
http://www.weberp.org/forum/showthread.php?tid=9268&pid=17591#pid17591
> Fix debtors import script as per AlexShen on forums.

- UserSettings.php
- includes/LanguageSetup.php
As per this thread
http://www.weberp.org/forum/showthread.php?tid=9269&pid=17594#pid17594
> Fixes to locale setting problems

- StockLocTransferReceive.php
http://www.weberp.org/forum/showthread.php?tid=9271 Files changed in commit:
StockLocTransferReceive.php
> Fix SQL to have a default value for the quality text field, as per

- AddCustomerNotes.php
- GLJournal.php
Use input type="date", with other related changes.
> Use Html5 date
